substitutions:
  name: climate-sense-bmp280
  friendly_name: Temp Humidity Pressure Sensor
  sleep_block_entity: input_boolean.block_esphome_sleep

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  on_boot:
    then:
      - lambda: |-
          Wire.begin();
      - output.turn_on: grove_power
  project:
    name: esphome.climate-sense-bme280
    version: "0.9"

esp8266:
  board: wio_node

logger:
  level: WARN

api:
  reboot_timeout: 0s

safe_mode:

ota:
  platform: esphome
  password: !secret ota_password
  on_begin:
    then:
      - deep_sleep.prevent: deep_sleep_control
  on_end:
    then:
      - deep_sleep.allow: deep_sleep_control

text_sensor:
  - platform: homeassistant
    name: "Block ESPHome Sleep State"
    id: block_sleep_state
    entity_id: ${sleep_block_entity}
    on_value:
      then:
        - if:
            condition:
              lambda: 'return id(block_sleep_state).state == "on";'
            then:
              - deep_sleep.prevent: deep_sleep_control
            else:
              - deep_sleep.allow: deep_sleep_control

i2c:
  scan: true

sensor:
  - platform: bme280_i2c
    temperature:
      name: "${name} Temperature"
      id: bme280_temperature
      filters:
        - offset: -1.0   # tune against a reference thermometer at steady state
    pressure:
      name: "${name} Pressure"
      id: bme280_pressure
    humidity:
      name: "${name} Humidity"
      id: bme280_humidity
    address: 0x76
    update_interval: 10s

output:
  - platform: gpio
    pin: 15
    inverted: false
    id: grove_power

deep_sleep:
  id: deep_sleep_control
  run_duration: 30s
  sleep_duration: 5min
