substitutions:
  name: climate-sense-bmp280
  friendly_name: Temp Humidity Pressure Sensor

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  platform: ESP8266
  board: wio_node

  on_boot:
    priority: -10
    then:
      - output.turn_on: grove_power
      - homeassistant.service:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.block_esphome_sleep
      - delay: 5s  # Wait a few seconds to ensure Home Assistant is ready
      - homeassistant.state:
          id: block_sleep_state
          entity_id: input_boolean.block_esphome_sleep
      - lambda: |-
          if (id(block_sleep_state).state == "on") {
            id(deep_sleep_control).prevent();
            ESP_LOGD("main", "Deep sleep is prevented due to Block ESPHome Sleep being ON.");
          } else {
            ESP_LOGD("main", "Deep sleep is allowed.");
          }

  project:
    name: esphome.climate-sense-bme280
    version: "0.7"

# Enable logging
logger:
  level: DEBUG  # WARN  # Reduce logging level

# Enable Home Assistant API
api:

homeassistant:
  # This will allow ESPHome to connect to Home Assistant and check the state of the virtual switch

i2c:
  # sda: D2
  # scl: D1
  scan: false

# Uncomment the OTA section to enable OTA updates
# ota:
#   platform: esphome
#   password: !secret ota_password
#   on_begin:
#     then:
#       - deep_sleep.prevent: deep_sleep_control
#   on_end:
#     then:
#       - deep_sleep.allow: deep_sleep_control

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light  # Enable Wi-Fi power save mode

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: "12345678"

captive_portal:

# Sleep to reduce the thermal impact of the MCU so close to the sensor
deep_sleep:
  id: deep_sleep_control
  run_duration: 20s  # Reduce active duration
  sleep_duration: 3min  # Increase sleep duration

sensor:
  - platform: bme280_i2c
    temperature:
      name: "${name} Temperature"
      oversampling: 16x
    pressure:
      name: "${name} Pressure"
      oversampling: 16x
    humidity:
      name: "${name} Humidity"
      oversampling: 16x
    address: 0x76
    update_interval: 180s  # Adjust to match sleep duration

output:
  - platform: gpio
    pin: 15
    inverted: false
    id: grove_power
