substitutions:
  name: climate-sense-bmp280
  friendly_name: Temp Humidity Pressure Sensor

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  platform: ESP8266
  board: wio_node

  on_boot:
    priority: -10
    then:
      - output.turn_on: grove_power

  project:
    name: esphome.climate-sense-bme280
    version: "0.6"

packages:
  esphome."climate-sense-bmp280": 
    url: https://github.com/jonnywifi/esphome/climate/sensorbme280
    ref: main
    files: [climate-sense-bme280.yaml]
    refresh: 0d

# Enable logging
logger:

# Enable Home Assistant API
api:

i2c:
  sda: D2
  scl: D1
  scan: false

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: "12345678"

captive_portal:

# Sleep to reduce the thermal impact of the MCU so close to the sensor
deep_sleep:
  run_duration: 30s
  sleep_duration: 2min

sensor:
  - platform: bme280_i2c
    temperature:
      name: "${name} Temperature"
      oversampling: 16x
    pressure:
      name: "${name} Pressure"
      oversampling: 16x
    humidity:
      name: "${name} Humidity"
      oversampling: 16x
    address: 0x76
    update_interval: 60s

output:
  - platform: gpio
    pin: 15
    inverted: false
    id: grove_power
